<a href="https://colab.research.google.com/github/StevenHSKim/Pytorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [41]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [42]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [43]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [46]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [48]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [49]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [51]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [53]:
#내적
torch.dot(tensor_a, tensor_b)

tensor(70)

In [58]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [59]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [61]:
#나머지 modulo
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [62]:
#나머지 remainder
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [63]:
#Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [64]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [65]:
#Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [66]:
tensor_a

tensor([1, 2, 3, 4])

In [69]:
#아래의 방법으로 tensor_a = tensor_a + tensor_b 이걸 표기 가능
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [70]:
tensor_a

tensor([11, 14, 17, 20])